[pytest]
pythonpath = .
addopts = -p no:cacheprovider
testpaths = tests
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated:starlette.testclient.StarletteDeprecationWarning
